config/routes.rb
Rails.application.routes.draw do
  # get 'reports/index'
  # get 'reports/new'
  # get 'reports/edit'
  # get 'reports/show'
  # get 'payments/index'
  # get 'payments/new'
  # get 'payments/edit'
  # get 'payments/show'
  # get 'teachers/index'
  # get 'teachers/new'
  # get 'teachers/edit'
  # get 'teachers/show'
  # get 'exam/index'
  # get 'exam/edit'
  # get 'exam/new'
  # get 'exam/show'
  # get 'students/index'
  # get 'students/new'
  # get 'students/edit'
  # get 'students/show'
 resources :books
 resources :students
 resources :exams
 resources :teachers
 resources :payments
 resources :reports
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord

    def self.expensive
        where('price > 500000')
    end

    def self.mahal(price)
        where('price>= ?',price)
    end
    
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new #untuk menampilkan data baru
    @book = Book.new
  end

  def create #untuk memproses data baru yang dimasukan di form new
    #render plain: params.inspect -> cara mengecek apa is params
    #titlr = params[:book]:[titlr] -> cara mengecek balikan params
    book = Book.new(resource_params)
    book.save
    flash[:notice] = "book has been created" #buat ngasi pesan pas udah di create
    #puts book.errors.masages
    redirect_to books_path
  end

  def edit #menampilkan data yang sudah di simpan di edit
    @book = Book.find(params[:id])
  end

  def update #melakukan proses ketika user mengedit data
    @book = Book.find(params[:id])
    @book.update(resource_params)
    flash[:notice] = "book has been Updated"
    redirect_to books_path(@book)
  end

  def destroy #untuk menghapus data
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "book has been Deleted"
    redirect_to books_path
  end

  def index #menampilkan seluruh data yang ada di database
    @books = Book.all
  end

  def show #menampilkan sebuah data secara detail
    id = params[:id]
    @book = Book.find(id)
    #render plain: id
    #render plain: @book.titlr
  end

  private
  def resource_params
    params.require(:book).permit(:titlr, :page, :price, :description)
  end

end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  def index
    #render 'index'

  end
  def home
    redirect_to controller: "home", action: "index"
  end
  
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
    def new
      @exam = Exam.new
    end
  
    def create
      exam = Exam.new(resource_params)
      exam.save
      flash[:notice] = "exam has been created" 
      redirect_to exams_path
    end
  
    def index
      @exams = Exam.all
    end
  
    def edit
      @exam = Exam.find(params[:id])
    end
  
    def update
      @exam = Exam.find(params[:id])
      @exam.update(resource_params)
      flash[:notice] = "exam has been Updated"
      redirect_to exams_path(@exam)
    end
  
    def show
      id = params[:id]
      @exam = exam.find(id)
    end
  
    def destroy
      @exam = Exam.find(params[:id])
      @exam.destroy
      flash[:notice] = "exam has been Deleted"
      redirect_to exams_path
    end
  
    private
    def resource_params
      params.require(:exam).permit(:title, :mapel, :duration, :nilFai, :status, :level, :student_id)
    end
  end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/exam_helper.rb
module ExamHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/books/edit.html.erb
<%= form_for(@book) do |f| %>
    <%= f.label :titlr %> </br>
    <%= f.text_field :titlr %> </br>

    <%= f.label :page %> </br>
    <%= f.text_field :page %> </br>

    <%= f.label :price %> </br>
    <%= f.text_field :price %> </br>


    <%= f.label :description %> </br>   
    <%= f.text_field :description %> </br> </br>

    <%= f.submit  %> </br>
   
<% end %>

app/views/books/index.html.erb
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

<table border="1" class="table table-dark">
    <tr align = "center">
        <td >Title</td>
        <td>Description</td>
        <td>Action</td>
    </tr>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.titlr %></td>
       <td><%= book.description %></td>
       <td><%= link_to 'Detail', book_path(book) %>
        | <%= link_to 'Edit', edit_book_path(book) %> 
        | <%= link_to 'Delete', book_path(book), method: :delete, data: {confirm: 'are you sure?'}%></td> 
    </tr>
    <% end %>
</table>

<%= link_to "New Book", new_book_path %>

app/views/books/new.html.erb
<%= form_for(@book) do |f| %>
    <%= f.label :titlr %> </br>
    <%= f.text_field :titlr %> </br>

    <%= f.label :page %> </br>
    <%= f.text_field :page %> </br>

    <%= f.label :price %> </br>
    <%= f.text_field :price %> </br>


    <%= f.label :description %> </br>   
    <%= f.text_field :description %> </br> </br>

    <%= f.submit "Save" %> </br>
   
<% end %>

app/views/books/show.html.erb
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

Titlr : <%= @book.titlr %> </br>
Page : <%= @book.page %> </br>
Price : <%= @book.price %> </br>
Description : <%= @book.description %> </br>

app/views/exams/edit.html.erb
<%= form_for(@exam) do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>

    <%= f.label :duration %> </br>
    <%= f.text_field :duration %> </br>


    <%= f.label :nilai %> </br>   
    <%= f.text_field :nilai %> </br> </br>

    <%= f.label :status %> </br>   
    <%= f.text_field :status %> </br> </br>

    <%= f.label :level %> </br>   
    <%= f.text_field :level %> </br> </br>

    <%= f.label :student_id %> </br>   
    <%= f.text_field :student_id %> </br> </br>

    <%= f.submit  %> </br>
   
<% end %>

app/views/exams/index.html.erb
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

<table border="1" class="table table-dark">
    <tr align = "center">
        <td >Title</td>
        <td>Mapel</td>
        <td>Duration</td>
        <td>Nilai</td>
        <td>Status</td>
        <td>Level</td>
        <td>Student ID</td>
        <td>Action</td>
    </tr>
    <% @exams.each do |exam| %>
    <tr>
      <td><%= exam.title %></td>
       <td><%= exam.mapel %></td>
       <td><%= exam.duration %></td>
       <td><%= exam.nilai %></td>
       <td><%= exam.status %></td>
       <td><%= exam.level %></td>
       <td><%= exam.student_id %></td>
       <td><%= link_to 'Detail', exam_path(exam) %>
        | <%= link_to 'Edit', edit_exam_path(exam) %> 
        | <%= link_to 'Delete', exam_path(exam), method: :delete, data: {confirm: 'are you sure?'}%></td> 
    </tr>
    <% end %>
</table>

<%= link_to "New Exam", new_exam_path %>

app/views/exams/new.html.erb
<%= form_for(@exam) do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>

    <%= f.label :duration %> </br>
    <%= f.text_field :duration %> </br>


    <%= f.label :nilai %> </br>   
    <%= f.text_field :nilai %> </br> </br>

    <%= f.label :status %> </br>   
    <%= f.text_field :status %> </br> </br>

    <%= f.label :level %> </br>   
    <%= f.text_field :level %> </br> </br>

    <%= f.label :student_id %> </br>   
    <%= f.text_field :student_id %> </br> </br>

    <%= f.submit "Save"  %> </br>
   
<% end %>

app/views/exams/show.html.erb
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

Title : <%= @book.title %> </br>
Mapel : <%= @book.mapel %> </br>
Duration : <%= @book.duration %> </br>
Description : <%= @book.description %> </br>