config/routes.rb
Rails.application.routes.draw do
  # get 'reports/index'
  # get 'reports/new'
  # get 'reports/edit'
  # get 'reports/show'
  # get 'payments/index'
  # get 'payments/new'
  # get 'payments/edit'
  # get 'payments/show'
  # get 'teachers/index'
  # get 'teachers/new'
  # get 'teachers/edit'
  # get 'teachers/show'
  # get 'exam/index'
  # get 'exam/edit'
  # get 'exam/new'
  # get 'exam/show'
  # get 'students/index'
  # get 'students/new'
  # get 'students/edit'
  # get 'students/show'
 resources :books
 resources :students
 resources :exams
 resources :teachers
 resources :payments
 resources :reports
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord

    def self.expensive
        where('price > 500000')
    end

    def self.mahal(price)
        where('price>= ?',price)
    end
    
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new #untuk menampilkan data baru
    @book = Book.new
  end

  def create #untuk memproses data baru yang dimasukan di form new
    #render plain: params.inspect -> cara mengecek apa is params
    #titlr = params[:book]:[titlr] -> cara mengecek balikan params
    book = Book.new(resource_params)
    book.save
    flash[:notice] = "book has been created" #buat ngasi pesan pas udah di create
    #puts book.errors.masages
    redirect_to books_path
  end

  def edit #menampilkan data yang sudah di simpan di edit
    @book = Book.find(params[:id])
  end

  def update #melakukan proses ketika user mengedit data
    @book = Book.find(params[:id])
    @book.update(resource_params)
    flash[:notice] = "book has been Updated"
    redirect_to books_path(@book)
  end

  def destroy #untuk menghapus data
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "book has been Deleted"
    redirect_to books_path
  end

  def index #menampilkan seluruh data yang ada di database
    @books = Book.all
  end

  def show #menampilkan sebuah data secara detail
    id = params[:id]
    @book = Book.find(id)
    #render plain: id
    #render plain: @book.titlr
  end

  private
  def resource_params
    params.require(:book).permit(:titlr, :page, :price, :description)
  end

end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  def index
    #render 'index'

  end
  def home
    redirect_to controller: "home", action: "index"
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def new
    @teacher = Teacher.new
  end

  def create
    teacher = Teacher.new(resource_params)
    teacher.save
    flash[:notice] = "teacher has been created" 
    redirect_to teachers_path
  end

  def index
    @teachers = Teacher.all
  end

  def edit
    @teacher = Teacher.find(params[:id])
  end

  def update
    @teacher = Teacher.find(params[:id])
    @teacher.update(resource_params)
    flash[:notice] = "teacher has been Updated"
    redirect_to teachers_path(@teacher)
  end

  def show
    id = params[:id]
    @teacher = Teacher.find(id)
  end

  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy
    flash[:notice] = "teacher has been Deleted"
    redirect_to teachers_path
  end

  private
  def resource_params
    params.require(:teacher).permit(:nik, :nama, :age, :kelas, :mapel)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/exam_helper.rb
module ExamHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/edit.html.erb
<%= form_for(@teacher) do |f| %>
    <%= f.label :nik %> </br>
    <%= f.text_field :nik %> </br>

    <%= f.label :nama %> </br>
    <%= f.text_field :nama %> </br>

    <%= f.label :age %> </br>
    <%= f.text_field :age %> </br>

    <%= f.label :kelas %> </br>   
    <%= f.text_field :kelas %> </br> </br>

    <%= f.label :mapel %> </br>   
    <%= f.text_field :mapel %> </br> </br>

    <%= f.submit  %> </br>
   
<% end %>

app/views/teachers/index.html.erb
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

<table border="1" class="table table-dark">
    <tr align = "center">
        <td >Nik</td>
        <td>Nama</td>
        <td>Age</td>
        <td>Kelas</td>
        <td>Mapel</td>
        <td>Action</td>
    </tr>
    <% @teachers.each do |teacher| %>
    <tr>
      <td><%= teacher.nik %></td>
       <td><%= teacher.nama %></td>
       <td><%= teacher.age %></td>
       <td><%= teacher.kelas %></td>
       <td><%= teacher.mapel %></td>
       <td><%= link_to 'Detail', teachers_path(teacher) %>
        | <%= link_to 'Edit', edit_teacher_path(teacher) %> 
        | <%= link_to 'Delete', teacher_path(teacher), method: :delete, data: {confirm: 'are you sure?'}%></td> 
    </tr>
    <% end %>
</table>

<%= link_to "New Teacher", new_teacher_path %>

app/views/teachers/new.html.erb
<%= form_for(@teacher) do |f| %>
    <%= f.label :nik %> </br>
    <%= f.text_field :nik %> </br>

    <%= f.label :nama %> </br>
    <%= f.text_field :nama %> </br>

    <%= f.label :age %> </br>
    <%= f.text_field :age %> </br>

    <%= f.label :kelas %> </br>   
    <%= f.text_field :kelas %> </br> </br>

    <%= f.label :mapel %> </br>   
    <%= f.text_field :mapel %> </br> </br>

    <%= f.submit "save" %> </br>
   
<% end %>

app/views/teachers/show.html.erb
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

nik : <%= @teacher.nik %> </br>
nama : <%= @teacher.nama %> </br>
age : <%= @teacher.age %> </br>
kelas : <%= @teacher.kelas %> </br>
mapel : <%= @teacher.mapel %> </br>