config/routes.rb
Rails.application.routes.draw do
  # get 'reports/index'
  # get 'reports/new'
  # get 'reports/edit'
  # get 'reports/show'
  # get 'payments/index'
  # get 'payments/new'
  # get 'payments/edit'
  # get 'payments/show'
  # get 'teachers/index'
  # get 'teachers/new'
  # get 'teachers/edit'
  # get 'teachers/show'
  # get 'exam/index'
  # get 'exam/edit'
  # get 'exam/new'
  # get 'exam/show'
  # get 'students/index'
  # get 'students/new'
  # get 'students/edit'
  # get 'students/show'
 resources :books
 resources :students
 resources :exams
 resources :teachers
 resources :payments
 resources :reports
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord

    def self.expensive
        where('price > 500000')
    end

    def self.mahal(price)
        where('price>= ?',price)
    end
    
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new #untuk menampilkan data baru
    @book = Book.new
  end

  def create #untuk memproses data baru yang dimasukan di form new
    #render plain: params.inspect -> cara mengecek apa is params
    #titlr = params[:book]:[titlr] -> cara mengecek balikan params
    book = Book.new(resource_params)
    book.save
    flash[:notice] = "book has been created" #buat ngasi pesan pas udah di create
    #puts book.errors.masages
    redirect_to books_path
  end

  def edit #menampilkan data yang sudah di simpan di edit
    @book = Book.find(params[:id])
  end

  def update #melakukan proses ketika user mengedit data
    @book = Book.find(params[:id])
    @book.update(resource_params)
    flash[:notice] = "book has been Updated"
    redirect_to books_path(@book)
  end

  def destroy #untuk menghapus data
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "book has been Deleted"
    redirect_to books_path
  end

  def index #menampilkan seluruh data yang ada di database
    @books = Book.all
  end

  def show #menampilkan sebuah data secara detail
    id = params[:id]
    @book = Book.find(id)
    #render plain: id
    #render plain: @book.titlr
  end

  private
  def resource_params
    params.require(:book).permit(:titlr, :page, :price, :description)
  end

end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  def index
    #render 'index'

  end
  def home
    redirect_to controller: "home", action: "index"
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @payment = Payment.new
  end

  def create
    payment = Payment.new(resource_params)
    payment.save
    flash[:notice] = "payment has been created" 
    redirect_to payments_path
  end

  def index
    @payments = Payment.all
  end

  def edit
    @payment = Payment.find(params[:id])
  end

  def update
    @payment = Payment.find(params[:id])
    @payment.update(resource_params)
    flash[:notice] = "payment has been Updated"
    redirect_to payments_path(@payment)
  end

  def show
    id = params[:id]
    @payment = Payment.find(id)
  end

  def destroy
    @payment = Payment.find(params[:id])
    @payment.destroy
    flash[:notice] = "payment has been Deleted"
    redirect_to payments_path
  end

  private
  def resource_params
    params.require(:payment).permit(:id_trassaction, :status, :upload)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/exam_helper.rb
module ExamHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/payments/edit.html.erb
<%= form_for(@payment) do |f| %>
    <%= f.label :id_trassaction %> </br>
    <%= f.text_field :id_trassaction %> </br>

    <%= f.label :status %> </br>
    <%= f.text_field :status %> </br>

    <%= f.label :upload %> </br>
    <%= f.text_field :upload %> </br>

    <%= f.submit  %> </br>
   
<% end %>

app/views/payments/index.html.erb
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

<table border="1" class="table table-dark">
    <tr align = "center">
        <td >ID Trassaction</td>
        <td>Status</td>
        <td>Upload</td>
        <td>Action</td>
    </tr>
    <% @payments.each do |payment| %>
    <tr>
      <td><%= payment.id_trassaction %></td>
       <td><%= payment.status %></td>
       <td><%= payment.upload %></td>
       <td><%= link_to 'Detail', payment_path(payment) %>
        | <%= link_to 'Edit', edit_payment_path(payment) %> 
        | <%= link_to 'Delete', payment_path(payment), method: :delete, data: {confirm: 'are you sure?'}%></td> 
    </tr>
    <% end %>
</table>

<%= link_to "New Payment", new_payment_path %>

app/views/payments/new.html.erb
<%= form_for(@payment) do |f| %>
    <%= f.label :id_trassaction %> </br>
    <%= f.text_field :id_trassaction %> </br>

    <%= f.label :status %> </br>
    <%= f.text_field :status %> </br>

    <%= f.label :upload %> </br>
    <%= f.text_field :upload %> </br>

    <%= f.submit "save"  %> </br>
   
<% end %>

app/views/payments/show.html.erb
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

id_trassaction : <%= @payment.id_trassaction %> </br>
status : <%= @payment.status %> </br>
upload : <%= @payment.upload %> </br>